site_name: JetBot
theme:
  name: "material"
  palette:
    primary: green
    secondary: light green

plugins:
  - search
#   - mkdocstrings

markdown_extensions:
  - pymdownx.superfences

nav:

  - Home:  https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Home
  - Bill of Materials: https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Bill-of-Materials
  - Hardware Setup: https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Hardware-Setup
  - Software Setup: https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Software-Setup
  - Examples: https://github.com/NVIDIA-AI-IOT/jetbot/wiki/examples
      